// <auto-generated />
using System;
using Kolos2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolos2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240611125714_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolos2.Models.Backpack", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterTitleCharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterTitleTitleId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("CharacterTitleCharacterId", "CharacterTitleTitleId");

                    b.ToTable("backpacks");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            ItemId = 1,
                            Amount = 30
                        },
                        new
                        {
                            CharacterId = 1,
                            ItemId = 2,
                            Amount = 40
                        },
                        new
                        {
                            CharacterId = 2,
                            ItemId = 1,
                            Amount = 22
                        },
                        new
                        {
                            CharacterId = 2,
                            ItemId = 2,
                            Amount = 34
                        });
                });

            modelBuilder.Entity("Kolos2.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BackpackCharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("BackpackItemId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BackpackCharacterId", "BackpackItemId");

                    b.ToTable("characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentWeight = 10,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            MaxWeight = 100
                        },
                        new
                        {
                            Id = 2,
                            CurrentWeight = 40,
                            FirstName = "Anna",
                            LastName = "Nowak",
                            MaxWeight = 200
                        });
                });

            modelBuilder.Entity("Kolos2.Models.CharacterTitle", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CharacterTitleCharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterTitleTitleId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "TitleId");

                    b.HasIndex("TitleId");

                    b.HasIndex("CharacterTitleCharacterId", "CharacterTitleTitleId");

                    b.ToTable("character_titles");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            TitleId = 1,
                            AcquiredAt = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 2,
                            TitleId = 2,
                            AcquiredAt = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CharacterId = 1,
                            TitleId = 2,
                            AcquiredAt = new DateTime(2010, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Kolos2.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BackpackCharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("BackpackItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BackpackCharacterId", "BackpackItemId");

                    b.ToTable("items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sword",
                            Weight = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shield",
                            Weight = 15
                        });
                });

            modelBuilder.Entity("Kolos2.Models.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("titles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Knight"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Barbarian"
                        });
                });

            modelBuilder.Entity("Kolos2.Models.Backpack", b =>
                {
                    b.HasOne("Kolos2.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos2.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos2.Models.CharacterTitle", null)
                        .WithMany("Backpacks")
                        .HasForeignKey("CharacterTitleCharacterId", "CharacterTitleTitleId");

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Kolos2.Models.Character", b =>
                {
                    b.HasOne("Kolos2.Models.Backpack", null)
                        .WithMany("Characters")
                        .HasForeignKey("BackpackCharacterId", "BackpackItemId");
                });

            modelBuilder.Entity("Kolos2.Models.CharacterTitle", b =>
                {
                    b.HasOne("Kolos2.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos2.Models.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos2.Models.CharacterTitle", null)
                        .WithMany("CharacterTitles")
                        .HasForeignKey("CharacterTitleCharacterId", "CharacterTitleTitleId");

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Kolos2.Models.Item", b =>
                {
                    b.HasOne("Kolos2.Models.Backpack", null)
                        .WithMany("Items")
                        .HasForeignKey("BackpackCharacterId", "BackpackItemId");
                });

            modelBuilder.Entity("Kolos2.Models.Backpack", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Kolos2.Models.CharacterTitle", b =>
                {
                    b.Navigation("Backpacks");

                    b.Navigation("CharacterTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
